ZON-4296: Add version field to liveblog module
ZeitOnline/zeit.content.article pull request #49
Opened 2018-01-05 09:06 UTC by kabbeck

Adds versioning to Liveblog element. New versions can be added to LiveblogVersions and current version might be set to "3" after a while, when old Liveblog version should not be used anymore.

2018-01-17 12:37 UTC, witsch requested changes
The test for the version should be added, imho 🙂

2018-01-17 12:37 UTC, witsch commented on src/zeit/content/article/edit/browser/tests/test_liveblog.py
> +        self.assertIn('3', b.getControl('Liveblog version').displayValue)
Perhaps you should also test that the version gets actually set on the article itself?

2018-01-18 12:24 UTC, kabbeck commented
Here is a test for old and new Liveblogs block attributes.

2018-01-25 17:08 UTC, witsch approved these changes
Nice!

2018-01-25 17:22 UTC, merged