SSL-159:  Add puzzleform module
ZeitOnline/zeit.content.article pull request #52
Opened 2018-03-21 08:08 UTC by knutgoetz

2018-03-21 08:28 UTC, wosc requested changes
Schick. An sich ziemlich straightforward (wenn auch mit Boilerplate beladen ;), ich hab noch Anmerkungen zur "schöneren" Formulierung.

2018-03-21 08:28 UTC, wosc commented on src/zeit/content/article/edit/interfaces.py
> +            zope.security.proxy.removeSecurityProxy(other))
Also an [anderen Stellen](https://github.com/ZeitOnline/zeit.cms/blob/master/src/zeit/cms/content/configure.zcml#L112) machen wir da tatsächlich eine Security-Declaration. Das ist zwar bürokratisch, ich würd aber removeProxy gern nur in Ausnahmefällen (und mit Kommentar wieso weshalb warum) verwenden.

2018-03-21 08:28 UTC, wosc commented on src/zeit/content/article/edit/tests/puzzleforms.xml
> +  <puzzle id="easter-puzzle">Osterrätsel</puzzle>
Weil ich grade aus Neugierde http://cms-backend.zeit.de:9000/cms/work/data/puzzleforms.xml angeschaut hab: dort ist noch ein Typo drin `easer-puzzle` (... also ich _hoffe_ dass es ein Typo ist, uns trau ich ja prinzipiell alles zu ;)

Kommen hier dann noch weitere Metadaten rein, damit Friedbert einen entsprechen iframe(?) rendern kann, oder was ist der Plan?

2018-03-21 08:28 UTC, wosc commented on src/zeit/content/article/edit/puzzleform.py
> +    def puzzle_type(self):
Ich hatte schonmal angefangen, für ziemlich genau diesen Use-Case Mechanik zu bauen, vgl. https://github.com/ZeitOnline/zeit.campus/blob/master/src/zeit/campus/article.py#L31 -- magst Du mal probieren, ob das hier auch passt?

2018-03-21 09:57 UTC, knutgoetz commented on src/zeit/content/article/edit/puzzleform.py
> +    def puzzle_type(self):
Versuche ich. Danke!

2018-03-21 09:57 UTC, knutgoetz commented on src/zeit/content/article/edit/tests/puzzleforms.xml
> +  <puzzle id="easter-puzzle">Osterrätsel</puzzle>
Jupp!  Oopserle

2018-03-22 09:37 UTC, wosc approved these changes
[puzzling](https://media.giphy.com/media/FLxXxBxkzqInu/giphy.gif)

2018-03-22 09:37 UTC, merged